// @ts-ignore - generated by esbuild during build
const { createApp } = require("./_app.cjs");
import type { VercelRequest, VercelResponse } from "@vercel/node";

const app = createApp();

export default function handler(req: VercelRequest, res: VercelResponse) {
  return app(req, res);
}
